### ISSUE TITLE
Treat 'hundertdreiundzwanzig' without the starting ''ein'

### ISSUE THREAD

**Issue by warichet** [walu2/zahlwort2num#1]
Hello,
i don't speak German, and maybe this kind of spelling is not correct.
but my ASR engine send me some number without the starting 'ein'.

I have modified the mult method to treat this case.

Best regards
Seb

```
  def mult(self, number, splitter, factor, fun):
        spliter = number.split(splitter)
        lenSplt = len(spliter)
        if lenSplt == 2:
            if splitter != 'und' and not spliter[0]:
              return factor +  fun(spliter[1])
            return fun(spliter[0]) * factor + fun(spliter[1])
        elif lenSplt == 1:
            return fun(spliter[0])
        else:
            raise ArgumentError('Given input cannot be properly parsed. Please double check if it has proper structure.')
```

**Comment by spatialbitz** [comment]
'hundert' (100) currently fails detection, but is used often instead of 'einhundert'. Would be great to add this.

**Comment by walu2** [comment]
Thanks for your good insights folks - appreciated 👌 

Would be wonderful - If you could create a PR for this and then this could be merged/bumped easily 🙏 
Somehow branching was disabled by default - sorry for that.

**Comment by walu2** [comment]
Fix from @spatialbitz's PR has been merged, version bumped - so Im closing

Thanks again
